version: '3.7'

networks:
  app-tier:
    driver: bridge

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=please_change_me
      - APPLICATION_STAGE_KEY=STAGE_OF_DEVELOPING
      - ALLOWED_HOSTS=192.168.99.100,0.0.0.0,127.0.0.1
      - DATABASE_URL=mariadb://root:dkffkah1!@172.30.1.45:3306/app_grouptango
    networks:
      - app-tier
  proxy:
    build:
      context: ./proxy
    volumes:
    - static_data:/vol/static
    ports:
      - "443:8090"
    depends_on:
      - app
    networks:
      - app-tier

volumes:
  static_data:


