# Generated by Django 3.1.7 on 2021-05-24 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('is_used', models.CharField(choices=[('Y', '사용'), ('N', '사용안함')], default='Y', max_length=1)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.settings')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/')),
                ('is_used', models.CharField(choices=[('Y', '사용'), ('N', '사용안함')], default='Y', max_length=1)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.settings')),
            ],
        ),
        migrations.CreateModel(
            name='TargetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TargetLocationUnmatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_location', models.CharField(max_length=30)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TargetLocationMatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_location', models.CharField(max_length=30)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TargetInterestUnmatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_interest', models.CharField(max_length=50)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TargetInterestMatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_interest', models.CharField(max_length=50)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TargetGenderUnmatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_gender', models.CharField(max_length=10)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TargetGenderMatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_gender', models.CharField(max_length=10)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TargetAgeUnmatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_age', models.CharField(max_length=10)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TargetAgeMatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_age', models.CharField(max_length=10)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord')),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=300)),
                ('is_correct', models.CharField(choices=[('Y', '정답'), ('N', '오답')], default='Y', max_length=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.quiz')),
            ],
        ),
    ]
