# Generated by Django 3.1 on 2020-11-15 12:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TargetLocationUnmatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_location', models.CharField(max_length=30)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TargetLocationMatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_location', models.CharField(max_length=30)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TargetInterestUnmatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_interest', models.CharField(max_length=50)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TargetInterestMatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_interest', models.CharField(max_length=50)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TargetGenderUnmatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_gender', models.CharField(max_length=10)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TargetGenderMatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_gender', models.CharField(max_length=10)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TargetAgeUnmatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_age', models.CharField(max_length=10)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TargetAgeMatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_age', models.CharField(max_length=10)),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.quiz')),
            ],
        ),
    ]
