# Generated by Django 3.1 on 2020-11-16 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_targetagematched_targetageunmatched_targetgendermatched_targetgenderunmatched_targetinterestmatched_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetagematched',
            name='target_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord'),
        ),
        migrations.AlterField(
            model_name='targetageunmatched',
            name='target_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord'),
        ),
        migrations.AlterField(
            model_name='targetgendermatched',
            name='target_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord'),
        ),
        migrations.AlterField(
            model_name='targetgenderunmatched',
            name='target_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord'),
        ),
        migrations.AlterField(
            model_name='targetinterestmatched',
            name='target_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord'),
        ),
        migrations.AlterField(
            model_name='targetinterestunmatched',
            name='target_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord'),
        ),
        migrations.AlterField(
            model_name='targetlocationmatched',
            name='target_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord'),
        ),
        migrations.AlterField(
            model_name='targetlocationunmatched',
            name='target_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.targetrecord'),
        ),
    ]
