# Generated by Django 3.1 on 2020-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_info_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
