# Generated by Django 3.1 on 2020-11-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201117_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logininfo',
            old_name='last_login_dt',
            new_name='last_login_at',
        ),
    ]
