# Generated by Django 3.1 on 2020-11-17 04:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0003_auto_20201116_1216'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reward_cap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField(default=django.utils.timezone.now)),
                ('daily_cap', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='transaction_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewarded', models.IntegerField(max_length=8)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.info')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commercial.video')),
            ],
        ),
        migrations.CreateModel(
            name='transaction_quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewarded', models.IntegerField(max_length=8)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.info')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commercial.quiz')),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commercial.quizchoices')),
            ],
        ),
    ]
