# Generated by Django 3.1 on 2020-11-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_quiz',
            old_name='quiz_id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='transaction_video',
            old_name='video_id',
            new_name='video',
        ),
    ]
