# Generated by Django 3.1 on 2020-11-17 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0002_auto_20201117_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_quiz',
            name='date_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction_video',
            name='date_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reward_cap',
            name='daily_cap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction_quiz',
            name='rewarded',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction_video',
            name='rewarded',
            field=models.IntegerField(),
        ),
    ]
