# Generated by Django 3.1 on 2020-11-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_auto_20201116_1216'),
        ('user', '0003_auto_20201117_1419'),
        ('treasure', '0003_auto_20201117_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reward_cap',
            new_name='RewardCap',
        ),
        migrations.RenameModel(
            old_name='transaction_quiz',
            new_name='TransactionQuiz',
        ),
        migrations.RenameModel(
            old_name='transaction_video',
            new_name='TransactionVideo',
        ),
    ]
